### GET request that fetches hall the hotels
GET http://localhost:8080/hotels/all
Content-Type: application/json

### GET request that fetches hotels by name
GET http://localhost:8080/hotels/Ibis
Content-Type: application/json

### POST request to checkin some guests
POST http://localhost:8080/hotels/checkin
Content-Type: application/json

{
    "hotelName": "Ibis",
    "nbGuests": 4
}

###